---
title: "Single-study simulation data generation"
author: "Trouble"
date: "09/11/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Clear the environment.
rm(list = ls())

# Packages.
library(metamedian)
library(tidyverse)

data(ss_data)

```

# Tasks

- Include `ggeasy` in the talk.

# Objective

# Simulation

## Calculate effects

```{r Get data}
get_effect <- function(this_tibble) {
  metamedian::effect_sd(
    centre = this_tibble$median,
    spread = this_tibble$iqr,
    n = this_tibble$n,
    centre_type = "median",
    spread_type = "iqr"
  )
}

ss_sim <- ss_data %>%
  mutate(
    arm_1_sd = map_dbl(sample_stats_1, get_effect),
    arm_2_sd = map_dbl(sample_stats_2, get_effect)
  )

```



```{r Calculate effects}
ss_sim <- ss_sim %>%
  mutate(
    m = map_dbl(sample_stats_1, "median"),
    m_var = arm_1_sd ^ 2,
    md = map_dbl(sample_stats_1, "median") - map_dbl(sample_stats_2, "median"),
    md_var = arm_1_sd ^ 2 + arm_2_sd ^ 2,
    lr = log(
      map_dbl(sample_stats_1, "median") /
        map_dbl(sample_stats_2, "median")
    ),
    lr_var = arm_1_sd ^ 2 / map_dbl(sample_stats_1, "median") ^ 2 +
      arm_2_sd ^ 2 / map_dbl(sample_stats_2, "median") ^ 2
  )
```

```{r Bundle effects gather}
ss_sim <- ss_sim %>% # Bundle measures of centre.
  mutate(effect_all = pmap(
    list(m, md, lr),
    .f = function(x, y, z) {
      tibble(m = x,
             md = y,
             lr = z)
    }
  )) %>%
  select(-m,-md,-lr,) %>%
  gather(key = "measure",
         value = "effect_var",
         m_var, md_var, lr_var) %>%
  mutate(measure = stringr::str_replace_all(measure, "_var", ""),
         arm_adj = stringr::str_replace_all(arm_adj, "sample_stats_2_", ""))

```

```{r Extract effect}
# Extract effect, depending on measure.
ss_sim <- ss_sim %>% 
  mutate(effect = 
           map2_dbl(measure, 
                    effect_all, 
                    .f = function(this_measure, effect_df) {
                      effect_df[this_measure] %>% as.numeric()
                    })
         )
```


# Confidence intervals

```{r Confidence intervals}
# Calculate confidence intervals.
ss_sim <- ss_sim %>% 
  mutate(
    ci_lb = effect - qnorm(0.975) * sqrt(effect_var),
    ci_ub = effect + qnorm(0.975) * sqrt(effect_var),
    # true_median_adj = 
    #   pmap_dbl(list(
    #     rdist,
    #     rpar1_adj,
    #     rpar2
    #   ), .f =
    #     function(x, y, z){
    #       dontpanic::any_dist(
    #         0.5,
    #         dist = x,
    #         par = list(y, z),
    #         type = "q"
    #       )
    #     } ),
    interval_width = ci_ub - ci_lb
    )

```


This is tricky because I need the adjustment variable to be conditional on the value of the `arm_adj` variable.

I'm going to try using predicate `.p` arguments for the firs time. This goes into the `map_if()` function. 

```{r Calculate true md and lr}
# Calculate true md and lr.

# First I need to create something I can pass into the first arg.

# How to do this the tidy way?
ss_sim$rpar1_arg <- as.numeric(0)
ss_sim$rpar1_arg[
  ss_sim$arm_adj == "adj"
] <- ss_sim$rpar1_adj[
  ss_sim$arm_adj == "adj"
]

ss_sim$rpar1_arg[
  ss_sim$arm_adj == "null"
] <- ss_sim$rpar1[
  ss_sim$arm_adj == "null"
]

ss_sim$rpar1_arg <- ss_sim$rpar1_arg %>% as.numeric()

# Check this worked as it should:
ss_sim$rpar1_arg %>% 
  table(useNA = "always") %>% 
  as_tibble() %>% 
  knitr::kable(col.names = c("Parameter", "n"))

```


```{r Get other median}
# Get other median.
test <- ss_sim %>% 
  head(1000) %>% 
  mutate(true_median_2 = pmap_dbl(
    .l = list(
      dist = rdist,
      rpar1_arg,
      rpar2
    ), 
    .f = function(dist, par1, par2) {
      if (length(par2) > 2) {pars <- par1} else {pars <- list(par1, par2)}
      
      dontpanic::any_dist(x = 0.5,
                          dist = dist,
                          par = pars,
                          type = "q")
    }
  ))
```

# Analysis of confidence intervals


```{r Calculate true effect}
# Calculate true effect.
ss_sim <- ss_sim %>% 
  mutate(
    true_effect = pmap_dbl(
      .l = list(
        measure = measure,
        m_1 = true_median,
        m_2 = true_median_2
      ),
      .f = function(measure, m_1, m_2) {
        if (measure == "m") {
          return(m_1)
        } else if (measure == "md") {
          return(m_1 - m_2) 
        } else if (measure == "lr") {
          return(
            log(m_1 / m_2)
          )
        } else {
          return("You fucked up again, nuff nuff.")
        }
      }
      
    )
  )

# Expect that the number of those that are non-zero to be the same as the number that are zero. 

ss_sim$true_effect %>% 
  table(useNA = "always") %>% 
  as_tibble() %>% 
  knitr::kable(col.names = c("Relative absolute bias", "n"))

ss_sim %>% 
  filter(true_effect == 0 ) %>% nrow() / 2

ss_sim %>% 
  filter(true_effect != 0 ) %>% nrow() / 4 # Why?

```

```{r Simulation results}
# Simulation results.
ss_sim <- ss_sim %>% 
  mutate(
    relative_interval_width = (ci_ub - ci_lb) / true_effect,
    relative_absolute_bias = abs(effect - true_effect) / true_effect,
    absolute_bias = abs(effect - true_effect),
    in_ci = ci_lb < true_effect & true_effect < ci_ub
  )
```

```{r Summarise results}
ss_summary <- ss_sim %>% # Summarise simulation results.
  group_by(n, rdist, rpar1_arg, measure) %>% 
  summarise(
    relative_interval_width = mean(relative_interval_width, na.rm = T),
    relative_absolute_bias = mean(relative_absolute_bias, na.rm = T),
    interval_width = mean(ci_ub - ci_lb),
    absolute_bias = mean(absolute_bias),
    coverage = sum(in_ci) / ss_par[[2]]
  )

# Take a look.
ss_summary %>% 
  knitr::kable()

# Note that dividing by 0 produces those infs - I think. Should check that.

```

```{r Plots}

# Plot everything without relative.
ss_summary %>% 
  ggplot(aes(x = rdist,
             y = coverage)) +
  geom_point(aes(size = absolute_bias,
                 colour = interval_width)) +
  # ggeasy::easy_rotate_x_labels() +
  facet_grid(n ~ measure) 

```

